name: My Bot Run

on:
  push

env:
  TOKEN: ${{secrets.TOKEN}}

jobs:
  Daily-Run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run App
        run: python my_bot.py